# Basics

Let's consdier the following Python List

There are a few points that we should note here
1. the list has differnt datatypes
2. each element 1,two and 3.0 is a full fledged python object and has it's own information
    a. Type information
    b. Reference count
    c. The value itself
3. The list just stores the reference to these objects
4. The main point to note here is that the memory is scattered and it's inefficient for numberic operations

In [30]:
py_list = [1,"two", 3.0]
for i in py_list:
    print(f'{i} is of type {type(i)} and is located at {id(i)}')

1 is of type <class 'int'> and is located at 140705101513640
two is of type <class 'str'> and is located at 2589548991648
3.0 is of type <class 'float'> and is located at 2589698837648


This is where numpy makes a great difference
1. It allows only same data type elements
2. The array only needs raw data, and the shape of the number of rows and columns

Few more points to note are
1. numpy "upcasts" the entire array -> in this case it upcasted the entire array to string
2. id() gives the memoery address for regular python object. 

In [31]:
import numpy as np

numpy_array = np.array(py_list)
for i in numpy_array:
    print(f'{i} is of type {type(i)} and is located at {i.data}')

1 is of type <class 'numpy.str_'> and is located at <memory at 0x0000025AEFAA1080>
two is of type <class 'numpy.str_'> and is located at <memory at 0x0000025AEFAA1BC0>
3.0 is of type <class 'numpy.str_'> and is located at <memory at 0x0000025AEFAA1BC0>


# List V/S Array

1. Once we define the size of a numpy array we cannot modify it, unlike we can append on list
2. Numpy array are faster as they are stored as a contiguous blocks of memory
3. They are 6 times more memory efficient than reqular lists

In [35]:
import sys
import timeit
py_list_1000 = []
append_operation = [py_list_1000.append(float(i)) for i in range(10000,1000000)]

print(f"py_list_1000 is of type {type(py_list_1000)} and it has {len(py_list_1000)} elements and the size of the list is {sys.getsizeof(py_list_1000)} bytes")

numpy_array_1000 = np.array(py_list_1000)
print(f"py_list_1000 is of type {type(numpy_array_1000)} and it has {len(numpy_array_1000)} elements and the size of the list is {sys.getsizeof(numpy_array_1000)} bytes")

"""
array.size v/s len()
array.nbytes v/s sys.getsizeof()

sys.getsizeof() this retuns the size of the python object, it has all the metadata
while nbytes only does the itemsize * elements in this case 8 bytes for int * 1000 elements
"""
print(f"py_list_1000 is of type {type(numpy_array_1000)} and it has {numpy_array_1000.size} elements and the size of the list is {numpy_array_1000.nbytes} bytes")

"""
Lets do some math operation on lists and arrays
"""
%timeit numpy_array_1000**2
%timeit [py_list_1000[i]**2 for i in range(len(py_list_1000))]


py_list_1000 is of type <class 'list'> and it has 990000 elements and the size of the list is 8448728 bytes
py_list_1000 is of type <class 'numpy.ndarray'> and it has 990000 elements and the size of the list is 7920112 bytes
py_list_1000 is of type <class 'numpy.ndarray'> and it has 990000 elements and the size of the list is 7920000 bytes
1.35 ms ± 26.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
80.4 ms ± 2.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# N-Dimensional Arrays
1. These are core to the numpy library

In [55]:
vector = np.array([1,2,3,4,5,6,7]) #One Dimensional Array
matrix = np.array([[1,2,3],[4,5,6]]) #Two Dimensional Array
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #Three Dimensional Array

print(f'{repr(vector)} is of {vector.ndim} dimensions')
print(f'{repr(matrix)} is of {matrix.ndim} dimensions')
print(f'{repr(tensor)} is of {tensor.ndim} dimensions')

array([1, 2, 3, 4, 5, 6, 7]) is of 1 dimensions
array([[1, 2, 3],
       [4, 5, 6]]) is of 2 dimensions
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]]) is of 3 dimensions


In [57]:
"""
Let's ty to do a few things
1. Vector = Get 2nd element of the vector
2. Matrix = Get 1st element of the 1st array and the last element of the 2nd array 
3. Tensor = Get the 
"""

print(vector[1])
print(matrix[0][0], matrix[1][-1])
print(matrix[0,0], matrix[1,-1])
print(tensor[0,0,0], tensor[-1,-1,-1])

2
1 6
1 6
1 8


## arange() and linspace()

In [ ]:
# Creating array using arange

arr1 = np.arange(10)
print(arr1)

even_arr1 = np.arange(0,10,2)
print(even_arr1)

# Using linspace to get floating point numbers as well
print(np.linspace(1,2)) # by default we get 50 values
print(np.linspace(1,2,5)) # limiting the elements

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]
[1.   1.25 1.5  1.75 2.  ]


## random.rand()

In [77]:
one_dim = np.random.rand(10)
print(one_dim)
two_dim = np.random.rand(2,4) # rows, columns
print(two_dim)
three_dim = np.random.rand(2,4,2) 
print(three_dim)

[0.24755926 0.12278829 0.04829644 0.24669538 0.17014655 0.0698342
 0.92659094 0.64762601 0.03723735 0.48779578]
[[0.8699658  0.1086665  0.69930077 0.24544428]
 [0.13144901 0.18382042 0.80152216 0.28677452]]
[[[0.04452322 0.54667014]
  [0.75136029 0.88903402]
  [0.43090447 0.7629315 ]
  [0.4569626  0.91115966]]

 [[0.91295003 0.62810503]
  [0.09256024 0.76065464]
  [0.88428353 0.9840755 ]
  [0.05671442 0.75878193]]]
