In [2]:
import numpy as np

### Numerical Python (NumPy)

1. Designed for ***faster numerical opeartions*** leveraging C++
2. Most of the udnerlying function use CPython API to use C++ code in python
3. The main core of NumPy is ***ndarray()*** - These are similar to python lists but are not as dynamic
    - We cannot change the size of an array.
    - Once a array is defiened we cannot append data to it, although we can udpate data in a array
    - Numpy array can have the same datatype
    - If the array elements have multiple datatypes, numpy will upcast the datatypes.

In [5]:
list1 = [1,"two",3.0]
print(list1)

# Appending data to a list
list1.append(4)
print(list1)

# Also note that each element has a different datatype
print(f'{list1[0]} is of type {type(list1[0])}\n{list1[1]} is of type {type(list1[1])}\n{list1[2]} is of type {type(list1[2])}\n{list1[3]} is of type {type(list1[3])}')

[1, 'two', 3.0]
[1, 'two', 3.0, 4]
1 is of type <class 'int'>
two is of type <class 'str'>
3.0 is of type <class 'float'>
4 is of type <class 'int'>


---
### Upcasting and Contiguous memory block

1. All the array elements are upcasted to the same data type (string in the below case)
2. Storing of the array elements happens in a contiguous block of memory unlike list where each element is stored seperately in the memory

In [35]:
arr1 = np.array([1,"two",3])

# Now the size of the aray is defined, we cannot add more element to arr1, but we can update the existing elements to it
arr1_details = f"""
Size fo the array is {arr1.size},
Array is of type {type(arr1)}
"""
print(arr1_details)

for i in range(0,len(arr1)):
    print(f"{arr1[i]} is of type {type(arr1[i])} and is stored at {arr1[i].data}")


Size fo the array is 3,
Array is of type <class 'numpy.ndarray'>

1 is of type <class 'numpy.str_'> and is stored at <memory at 0x000001C7FFA4D080>
two is of type <class 'numpy.str_'> and is stored at <memory at 0x000001C7FFA4D080>
3 is of type <class 'numpy.str_'> and is stored at <memory at 0x000001C7FFA4D080>


---
### Differnet ways to create numpy array
1. Converting an exisitng list/tuple to np array
2. Create array with constant values (zeros, ones, or any other desired value)
3. Using inbuit function 
    a. arange() - similar to range funciton in python
    b. linspace() - helps generate floating point numbers within the given range
    Note - by default linspace will give you 50 values, but we can limit it with the last paramater

In [47]:
list2 = [1,2,3,4,5,6,7]
print(f'list2 is of type {type(list2)} and has the following elements {list2}')

# Converting an existing list/type to np array
arr2 = np.array(list2)
print(f'arr2 is of type {type(arr2)} and has the following elements {arr2}')


print(f'One dimensional array {np.zeros(5)}') # array with zeros - 5 columns
print(f'Two dimensional array {np.zeros([5,2])}') # array with zeros - 5  columns and 2 rows
print(f'Three dimensional arry of 1s {np.ones([2,2,2])}') # 3 dim array of 1s

""" Array with constant values aprat from 1 and 0
There are two ways to do it
1. Create an empty array then fill the desired number
2. use the full function instead
"""
const_val_arr = np.empty(10, dtype = float)
const_val_arr.fill(6)
print(const_val_arr)

print(np.full(5,10)) # Directly creates a array with 5 elements with 10 as the constant value

print(f"""
Using the arange function we get = 
{np.arange(4)},
Using the linspace fucntion we get = 
{np.linspace(4,5,5)}
""")


list2 is of type <class 'list'> and has the following elements [1, 2, 3, 4, 5, 6, 7]
arr2 is of type <class 'numpy.ndarray'> and has the following elements [1 2 3 4 5 6 7]
One dimensional array [0. 0. 0. 0. 0.]
Two dimensional array [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Three dimensional arry of 1s [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
[10 10 10 10 10]

Using the arange function we get = 
[0 1 2 3],
Using the linspace fucntion we get = 
[4.   4.25 4.5  4.75 5.  ]



---
### Attributes of an array

1. type - .dtype
2. dimension - .ndim
3. shape - .shape
4. size - .size (signifies number of elements in each dimension)

In [64]:
# let's try to determine the attributes of arraya

one_dim = np.array([1,2,3,4,5,6],dtype = np.int32) # default type would be int64
two_dim = np.array([[1,2,3],[4,5,6]])
three_dim = np.array([[[1,2],[3,4]],[[5,6],[0,0]]])

msg1 = f'''
{one_dim} is of {one_dim.ndim} dimension, has {one_dim.shape} shape, it's size is {one_dim.size} and is of type {one_dim.dtype}
{two_dim} is of {two_dim.ndim} dimension, has {two_dim.shape} shape, it's size is {two_dim.size} and is of type {two_dim.dtype}
{three_dim} is of {three_dim.ndim} dimension, has {three_dim.shape} shape, it's size is {three_dim.size} and is of type {three_dim.dtype}
'''

print(msg1)


[1 2 3 4 5 6] is of 1 dimension, has (6,) shape, it's size is 6 and is of type int32
[[1 2 3]
 [4 5 6]] is of 2 dimension, has (2, 3) shape, it's size is 6 and is of type int64
[[[1 2]
  [3 4]]

 [[5 6]
  [0 0]]] is of 3 dimension, has (2, 2, 2) shape, it's size is 8 and is of type int64



---
### Manipulating Arrays

1. Adding = .append
2. Removing = .remove 
3. Sorting = .sort
4. Updating = 

In [ ]:
"""
Note -
Appending / Inserting an element in a Numpy array creates a new array at a different memeory location
"""
og_arr = np.array([1,2,3,4])

print(f'This {og_arr} is the original array at location {og_arr.__array_interface__['data'][0]}')

insert_arr = np.insert(og_arr,4,5) # this inserts 20 at location 3
print(f'This {insert_arr} has the following python memeory view {insert_arr.__array_interface__['data'][0]}')

append_arr = np.append(og_arr,5) # this appends 5 at the end of the array
print(f'This {append_arr} has the following python memeory view {append_arr.__array_interface__['data'][0]}')

# Deleting an element from an array
del_arr = np.delete(append_arr,4)
print(f'{del_arr} was created at memory location {del_arr.__array_interface__['data'][0]}')






This [1 2 3 4] is the original array at location 1957952086880
This [1 2 3 4 5] has the following python memeory view 1957885800096
This [1 2 3 4 5] has the following python memeory view 1957885456624
[1 2 3 4] was created at memory location 1957952089504
{'data': (1957885456624, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (5,), 'version': 3}


---
### Copies and Views in Numpy

COPY - create these when you need isolation
1. This creates a deep copy
2. New array object is created at a <u>**different memory location**</u>
3. Changes in original array do not affect copied array
2. Views - Same location is being referenced - this is a copy created using assignment, any changes to the original and the copy reflect on each other

VIEW - create these when memory matters and you want to sclice and dice the data keeping the same structure
1. Creates a new array object but has the <u>**same memory location**</u>
2. Modifying one changes the other.
3. The only change is a new array object is created

.base - return None when an array is a copy

NOTE -
cp_arr = og_arr, This is just assignment, i.e., we are just givin og_arr a different alias an nothing will happend here cp_arr will be same as og_arr in all aspects,
there just would be a name difference 



In [ ]:
original_arr = np.array([1,2,3,4])

print(f'Original array contains {original_arr} and is located at {original_arr.__array_interface__['data'][0]}')

copy_arr = original_arr.copy()
# Check 1 - Memory Location = Different
print(f'Copied array contains {copy_arr} and is located at {copy_arr.__array_interface__['data'][0]}')
# Check 2 - Element Update = Creates a deep copy, changes are not passed on 
copy_arr[0] = 67 

# Creating a view of the original array
view_arr = original_arr.view()
# Check 1 - Memory Location = Same
print(f'View array contains {view_arr} and is located at {view_arr.__array_interface__['data'][0]}')
# Check 2 - Element Update = chagtes are passed on
view_arr[0] = 67
print(f'view_arr = {view_arr}, original_arr = {original_arr}')

# Final Check - Copy/View
print(f'copy_arr = {copy_arr.base}, view_arr = {view_arr.base}') # copyu_arr return None as its a deep copy and own the data



Original array contains [1 2 3 4] and is located at 1451917990656
Copied array contains [1 2 3 4] and is located at 1451917991648
View array contains [1 2 3 4] and is located at 1451917990656
view_arr = [67  2  3  4], original_arr = [67  2  3  4]
copy_arr = None, view_arr = [67  2  3  4]


---

### Reshaping Arrays

RESHAPE
1. Creates a reshaped **VIEW** of the array
2. All rules of views apply to reshape as well

FLATTEN

REOLVE



In [ ]:
arr3 = np.arange(1,13) # this creates a one dim array with 12 elements
print(f'{arr3} has {arr3.ndim} dimension')
print(arr3.__array_interface__['data'][0])

two_dim_arr = np.reshape(arr3, (3,4))
print(f'{two_dim_arr} has {two_dim_arr.ndim} dimension')
print(two_dim_arr.__array_interface__['data'][0])

two_dim_arr[1][0]= 67

print(arr3, two_dim_arr) # This confirms that reshape creates a view and changes to view also changes the original
print("-----------------------------")

"""
Flatenning the arrays
"""
flat_test = np.random.rand(3,4)

flat_arr = np.reshape(flat_test,-1) # move one dim earlier

print(f'Original array was \n {flat_test},\n\n Flatenned array is \n{flat_arr}')


[ 1  2  3  4  5  6  7  8  9 10 11 12] has 1 dimension
1451868294816
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] has 2 dimension
1451868294816
[ 1  2  3  4 67  6  7  8  9 10 11 12] [[ 1  2  3  4]
 [67  6  7  8]
 [ 9 10 11 12]]
-----------------------------
Original array was 
 [[0.90572979 0.5687588  0.45090711 0.44984114]
 [0.69794183 0.4636879  0.69272279 0.27854741]
 [0.4608303  0.07324363 0.62227784 0.23602579]],

 Flatenned array is 
[0.90572979 0.5687588  0.45090711 0.44984114 0.69794183 0.4636879
 0.69272279 0.27854741 0.4608303  0.07324363 0.62227784 0.23602579]
